export const skillNameMap: { [leaf: string]: string } = {
  brawl: 'Brawl (Br)',
  gunnery: 'Gunnery (Ag)',
  melee: 'Melee (Br)',
  rangedHeavy: 'Ranged (Heavy) (Ag)',
  rangedLight: 'Ranged (Light) (Ag)',
  athletics: 'Athletics (Br)',
  compHacking: 'Comp (Hacking) (Int)',
  compSysops: 'Comp (Sysops) (Int)',
  cool: 'Cool (Pr)',
  coordination: 'Coordination (Ag)',
  discipline: 'Discipline (Will)',
  driving: 'Driving (Ag)',
  mechanics: 'Mechanics (Int)',
  medicine: 'Medicine (Int)',
  operating: 'Operating (ag)',
  perception: 'Perception (Cun)',
  piloting: 'Piloting (Ag)',
  resilience: 'Resilience (Br)',
  skullduggery: 'Skullduggery (Cun)',
  stealth: 'Stealth (Ag)',
  streetwise: 'Streetwise (Cun)',
  survival: 'Survival (Cun)',
  vigilance: 'Vigilance (Will)',
  charm: 'Charm (Pr)',
  coercion: 'Coercion (Will)',
  deception: 'Deception (Cun)',
  leadership: 'Leadership (Pr)',
  negotiation: 'Negotiation (Pr)',
  science: 'Science (Int)',
  society: 'Society (Int)',
  theNet: 'The Net (Int)',
}
